In [1]:
import os
import yaml
import pandas as pd
from pandas import json_normalize
from yaml import safe_load
from tqdm import tqdm

In [28]:
# Extract File Names
folder_path = 'data'

file_names = [f for f in os.listdir(folder_path) if f.endswith('.yaml')]

print(f"Total files found: {len(file_names)}")
print("First 5 files:", file_names[:5])

Total files found: 5055
First 5 files: ['1001349.yaml', '1001351.yaml', '1001353.yaml', '1004729.yaml', '1007655.yaml']

In [29]:
# to extract yaml files 
final_df = pd.DataFrame()
counter = 1

for file_name in tqdm(file_names, desc="Loading match files"):
    full_path = os.path.join(folder_path, file_name)
    
    with open(full_path, 'r') as f:
        df = pd.json_normalize(safe_load(f), max_level=1)
        df['match_id'] = counter
        final_df = pd.concat([final_df, df], ignore_index=True)
        counter += 1

final_df

Loading match files: 100%|██████████| 5055/5055 [14:04<00:00,  5.99it/s]

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.dates,info.gender,info.match_type,info.outcome,info.overs,...,info.teams,info.toss,info.umpires,info.venue,match_id,info.city,info.match_type_number,info.neutral_venue,info.supersubs,info.bowl_out
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-18,2,6,[2017-02-17],male,T20,"{'by': {'wickets': 5}, 'winner': 'Sri Lanka'}",20,...,"[Australia, Sri Lanka]","{'decision': 'field', 'winner': 'Sri Lanka'}","[MD Martell, P Wilson]",Melbourne Cricket Ground,1,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-19,2,6,[2017-02-19],male,T20,"{'by': {'wickets': 2}, 'winner': 'Sri Lanka'}",20,...,"[Australia, Sri Lanka]","{'decision': 'field', 'winner': 'Sri Lanka'}","[SD Fry, SJ Nogajski]","Simonds Stadium, South Geelong",2,Victoria,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-23,1,6,[2017-02-22],male,T20,"{'by': {'runs': 41}, 'winner': 'Australia'}",20,...,"[Australia, Sri Lanka]","{'decision': 'field', 'winner': 'Sri Lanka'}","[MD Martell, P Wilson]",Adelaide Oval,3,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",0.91,2016-09-12,1,6,[2016-09-05],male,T20,"{'by': {'runs': 40}, 'winner': 'Hong Kong'}",20,...,"[Ireland, Hong Kong]","{'decision': 'bat', 'winner': 'Hong Kong'}","[R Black, AJ Neill]","Bready Cricket Club, Magheramason",4,Londonderry,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.91,2016-06-19,1,6,[2016-06-18],male,T20,"{'by': {'runs': 2}, 'winner': 'Zimbabwe'}",20,...,"[Zimbabwe, India]","{'decision': 'field', 'winner': 'India'}","[TJ Matibiri, RB Tiffin]",Harare Sports Club,5,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5050,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.91,2016-03-05,2,6,[2016-03-04],male,T20,"{'by': {'wickets': 6}, 'winner': 'Pakistan'}",20,...,"[Pakistan, Sri Lanka]","{'decision': 'field', 'winner': 'Pakistan'}","[AK Chaudhary, Enamul Haque]",Shere Bangla National Stadium,5051,Mirpur,NaN,1.0,NaN,NaN
5051,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",0.91,2016-03-08,1,6,[2016-03-06],male,T20,"{'by': {'wickets': 8}, 'winner': 'India'}",20,...,"[Bangladesh, India]","{'decision': 'field', 'winner': 'India'}","[RSA Palliyaguruge, Shozab Raza]",Shere Bangla National Stadium,5052,Mirpur,NaN,NaN,NaN,NaN
5052,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.91,2016-02-03,1,6,[2016-02-03],male,T20,"{'by': {'runs': 84}, 'winner': 'Netherlands'}",20,...,"[United Arab Emirates, Netherlands]","{'decision': 'field', 'winner': 'United Arab E...","[CK Nandan, Sarika Prasad]",ICC Academy,5053,Dubai,NaN,NaN,NaN,NaN
5053,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2016-09-12,1,6,[2016-09-06],male,T20,"{'by': {'runs': 85}, 'winner': 'Australia'}",20,...,"[Sri Lanka, Australia]","{'decision': 'field', 'winner': 'Sri Lanka'}","[REJ Martinesz, RR Wimalasiri]",Pallekele International Cricket Stadium,5054,NaN,NaN,NaN,NaN,NaN
5054,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.91,2016-09-12,1,6,[2016-09-09],male,T20,"{'by': {'wickets': 4}, 'winner': 'Australia'}",20,...,"[Sri Lanka, Australia]","{'decision': 'bat', 'winner': 'Sri Lanka'}","[REJ Martinesz, RSA Palliyaguruge]",R Premadasa Stadium,5055,Colombo,NaN,NaN,NaN,NaN

In [33]:
final_df.info(22)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5055 entries, 0 to 5054
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   innings                 5055 non-null   object
 1   meta.data_version       5055 non-null   float64
 2   meta.created            5055 non-null   object
 3   meta.revision           5055 non-null   int64
 4   info.balls_per_over     5055 non-null   int64
 5   info.dates              5055 non-null   object
 6   info.gender             5055 non-null   object
 7   info.match_type         5055 non-null   object
 8   info.outcome            5055 non-null   object
 9   info.overs              5055 non-null   int64
 10  info.player_of_match    4572 non-null   object
 11  info.players            5055 non-null   object
 12  info.registry           5055 non-null   object
 13  info.teams              5055 non-null   object
 14  info.toss               5055 non-null   object
 15  info.umpires            4750 non-null   object
 16  info.venue              5055 non-null   object
 17  match_id                5055 non-null   int64
 18  info.city               4876 non-null   object
 19  info.match_type_number  4380 non-null   float64
 20  info.neutral_venue      283 non-null    float64
 21  info.supersubs          1 non-null      object
 22  info.bowl_out           2 non-null      object
dtypes: float64(3), int64(4), object(16)
memory usage: 908.4+ KB

In [35]:
# relevant columns
final_df = final_df[[
    'match_id',
    'info.dates',
    'info.venue',
    'info.city',
    'info.gender',
    'info.match_type',
    'info.overs',
    'info.teams',
    'info.umpires',
    'info.toss',
    'info.outcome',
    'innings',
]].rename(columns={
    'info.dates'      : 'date',
    'info.venue'      : 'venue',
    'info.city'       : 'city',
    'info.gender'     : 'gender',
    'info.match_type' : 'match_type',
    'info.overs'      : 'overs',
    'info.teams'      : 'teams',
    'info.umpires'    : 'umpires',
    'info.toss'       : 'toss',
    'info.outcome'    : 'outcome',
})

In [36]:
final_df.head()

,match_id,date,venue,city,gender,match_type,overs,teams,umpires,toss,outcome,innings
0,1,[2017-02-17],Melbourne Cricket Ground,NaN,male,T20,20,"[Australia, Sri Lanka]","[MD Martell, P Wilson]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'wickets': 5}, 'winner': 'Sri Lanka'}","[{'1st innings': {'team': 'Australia', 'delive..."
1,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,T20,20,"[Australia, Sri Lanka]","[SD Fry, SJ Nogajski]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'wickets': 2}, 'winner': 'Sri Lanka'}","[{'1st innings': {'team': 'Australia', 'delive..."
2,3,[2017-02-22],Adelaide Oval,NaN,male,T20,20,"[Australia, Sri Lanka]","[MD Martell, P Wilson]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'runs': 41}, 'winner': 'Australia'}","[{'1st innings': {'team': 'Australia', 'delive..."
3,4,[2016-09-05],"Bready Cricket Club, Magheramason",Londonderry,male,T20,20,"[Ireland, Hong Kong]","[R Black, AJ Neill]","{'decision': 'bat', 'winner': 'Hong Kong'}","{'by': {'runs': 40}, 'winner': 'Hong Kong'}","[{'1st innings': {'team': 'Hong Kong', 'delive..."
4,5,[2016-06-18],Harare Sports Club,NaN,male,T20,20,"[Zimbabwe, India]","[TJ Matibiri, RB Tiffin]","{'decision': 'field', 'winner': 'India'}","{'by': {'runs': 2}, 'winner': 'Zimbabwe'}","[{'1st innings': {'team': 'Zimbabwe', 'deliver..."

In [37]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5055 entries, 0 to 5054
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   match_id    5055 non-null   int64
 1   date        5055 non-null   object
 2   venue       5055 non-null   object
 3   city        4876 non-null   object
 4   gender      5055 non-null   object
 5   match_type  5055 non-null   object
 6   overs       5055 non-null   int64
 7   teams       5055 non-null   object
 8   umpires     4750 non-null   object
 9   toss        5055 non-null   object
 10  outcome     5055 non-null   object
 11  innings     5055 non-null   object
dtypes: int64(2), object(10)
memory usage: 474.0+ KB

In [38]:
final_df = final_df[(final_df['overs'] == 20) & (final_df['match_type'] == 'T20')]

print(f"Shape after filtering: {final_df.shape}")
final_df.head()

Shape after filtering: (5040, 12)

,match_id,date,venue,city,gender,match_type,overs,teams,umpires,toss,outcome,innings
0,1,[2017-02-17],Melbourne Cricket Ground,NaN,male,T20,20,"[Australia, Sri Lanka]","[MD Martell, P Wilson]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'wickets': 5}, 'winner': 'Sri Lanka'}","[{'1st innings': {'team': 'Australia', 'delive..."
1,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,T20,20,"[Australia, Sri Lanka]","[SD Fry, SJ Nogajski]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'wickets': 2}, 'winner': 'Sri Lanka'}","[{'1st innings': {'team': 'Australia', 'delive..."
2,3,[2017-02-22],Adelaide Oval,NaN,male,T20,20,"[Australia, Sri Lanka]","[MD Martell, P Wilson]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'runs': 41}, 'winner': 'Australia'}","[{'1st innings': {'team': 'Australia', 'delive..."
3,4,[2016-09-05],"Bready Cricket Club, Magheramason",Londonderry,male,T20,20,"[Ireland, Hong Kong]","[R Black, AJ Neill]","{'decision': 'bat', 'winner': 'Hong Kong'}","{'by': {'runs': 40}, 'winner': 'Hong Kong'}","[{'1st innings': {'team': 'Hong Kong', 'delive..."
4,5,[2016-06-18],Harare Sports Club,NaN,male,T20,20,"[Zimbabwe, India]","[TJ Matibiri, RB Tiffin]","{'decision': 'field', 'winner': 'India'}","{'by': {'runs': 2}, 'winner': 'Zimbabwe'}","[{'1st innings': {'team': 'Zimbabwe', 'deliver..."

In [39]:
final_df = final_df.dropna()

print(f"Shape after dropping nulls: {final_df.shape}")
final_df.head()

Shape after dropping nulls: (4557, 12)

,match_id,date,venue,city,gender,match_type,overs,teams,umpires,toss,outcome,innings
1,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,T20,20,"[Australia, Sri Lanka]","[SD Fry, SJ Nogajski]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'wickets': 2}, 'winner': 'Sri Lanka'}","[{'1st innings': {'team': 'Australia', 'delive..."
3,4,[2016-09-05],"Bready Cricket Club, Magheramason",Londonderry,male,T20,20,"[Ireland, Hong Kong]","[R Black, AJ Neill]","{'decision': 'bat', 'winner': 'Hong Kong'}","{'by': {'runs': 40}, 'winner': 'Hong Kong'}","[{'1st innings': {'team': 'Hong Kong', 'delive..."
7,8,[2017-01-03],McLean Park,Napier,male,T20,20,"[New Zealand, Bangladesh]","[SB Haig, WR Knights]","{'decision': 'bat', 'winner': 'Bangladesh'}","{'by': {'wickets': 6}, 'winner': 'New Zealand'}","[{'1st innings': {'team': 'Bangladesh', 'deliv..."
8,9,[2017-01-06],Bay Oval,Mount Maunganui,male,T20,20,"[New Zealand, Bangladesh]","[CM Brown, SB Haig]","{'decision': 'field', 'winner': 'Bangladesh'}","{'by': {'runs': 47}, 'winner': 'New Zealand'}","[{'1st innings': {'team': 'New Zealand', 'deli..."
9,10,[2017-01-08],Bay Oval,Mount Maunganui,male,T20,20,"[New Zealand, Bangladesh]","[CM Brown, WR Knights]","{'decision': 'field', 'winner': 'Bangladesh'}","{'by': {'runs': 27}, 'winner': 'New Zealand'}","[{'1st innings': {'team': 'New Zealand', 'deli..."

In [40]:
final_df['gender'].value_counts()

gender
male      2878
female    1679
Name: count, dtype: int64

In [45]:
import pickle

pickle.dump(final_df, open('dataset_level1.pkl', 'wb'))

In [27]:
import pickle
df = pickle.load(open('dataset_level1.pkl', 'rb'))
df.head()

,match_id,date,venue,city,gender,match_type,overs,teams,umpires,toss,outcome,innings
1,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,T20,20,"[Australia, Sri Lanka]","[SD Fry, SJ Nogajski]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'wickets': 2}, 'winner': 'Sri Lanka'}","[{'1st innings': {'team': 'Australia', 'delive..."
3,4,[2016-09-05],"Bready Cricket Club, Magheramason",Londonderry,male,T20,20,"[Ireland, Hong Kong]","[R Black, AJ Neill]","{'decision': 'bat', 'winner': 'Hong Kong'}","{'by': {'runs': 40}, 'winner': 'Hong Kong'}","[{'1st innings': {'team': 'Hong Kong', 'delive..."
7,8,[2017-01-03],McLean Park,Napier,male,T20,20,"[New Zealand, Bangladesh]","[SB Haig, WR Knights]","{'decision': 'bat', 'winner': 'Bangladesh'}","{'by': {'wickets': 6}, 'winner': 'New Zealand'}","[{'1st innings': {'team': 'Bangladesh', 'deliv..."
8,9,[2017-01-06],Bay Oval,Mount Maunganui,male,T20,20,"[New Zealand, Bangladesh]","[CM Brown, SB Haig]","{'decision': 'field', 'winner': 'Bangladesh'}","{'by': {'runs': 47}, 'winner': 'New Zealand'}","[{'1st innings': {'team': 'New Zealand', 'deli..."
9,10,[2017-01-08],Bay Oval,Mount Maunganui,male,T20,20,"[New Zealand, Bangladesh]","[CM Brown, WR Knights]","{'decision': 'field', 'winner': 'Bangladesh'}","{'by': {'runs': 27}, 'winner': 'New Zealand'}","[{'1st innings': {'team': 'New Zealand', 'deli..."

In [28]:
# Extract ball by ball data for every match's first innings

# for each match
all_rows = []

for index, row in tqdm(df.iterrows(), desc="Extracting deliveries", total=len(df)):

    ball_of_match      = []
    batsman            = []
    bowler             = []
    runs               = []
    player_dismissed   = []
    teams              = []
    batting_team       = []
    match_id           = []
    city               = []
    venue              = []

    try:
        deliveries = row['innings'][0]['1st innings']['deliveries']
    except:
        continue  

    for ball in deliveries:
        for key in ball.keys():
            match_id.append(row['match_id'])
            batting_team.append(row['innings'][0]['1st innings']['team'])
            teams.append(row['teams'])
            ball_of_match.append(key)
            batsman.append(ball[key]['batsman'])
            bowler.append(ball[key]['bowler'])
            runs.append(ball[key]['runs']['total'])
            city.append(row['city'])
            venue.append(row['venue'])

            # Get dismissed player if wicket fell, else '0'
            try:
                player_dismissed.append(ball[key]['wicket']['player_out'])
            except:
                player_dismissed.append('0')

    loop_df = pd.DataFrame({
        'match_id'         : match_id,
        'teams'            : teams,
        'batting_team'     : batting_team,
        'ball'             : ball_of_match,
        'batsman'          : batsman,
        'bowler'           : bowler,
        'runs'             : runs,
        'player_dismissed' : player_dismissed,
        'city'             : city,
        'venue'            : venue,
    })

    all_rows.append(loop_df)


delivery_df = pd.concat(all_rows, ignore_index=True)

print(f"Shape: {delivery_df.shape}")
delivery_df.head(10)

Extracting deliveries: 100%|██████████| 4557/4557 [00:13<00:00, 340.33it/s]

Shape: (553786, 10)

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,2,"[Australia, Sri Lanka]",Australia,0.1,M Klinger,SL Malinga,0,0,Victoria,"Simonds Stadium, South Geelong"
1,2,"[Australia, Sri Lanka]",Australia,0.2,M Klinger,SL Malinga,1,0,Victoria,"Simonds Stadium, South Geelong"
2,2,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,0,0,Victoria,"Simonds Stadium, South Geelong"
3,2,"[Australia, Sri Lanka]",Australia,0.4,AJ Finch,SL Malinga,4,0,Victoria,"Simonds Stadium, South Geelong"
4,2,"[Australia, Sri Lanka]",Australia,0.5,AJ Finch,SL Malinga,1,0,Victoria,"Simonds Stadium, South Geelong"
5,2,"[Australia, Sri Lanka]",Australia,0.6,M Klinger,SL Malinga,1,0,Victoria,"Simonds Stadium, South Geelong"
6,2,"[Australia, Sri Lanka]",Australia,1.1,M Klinger,KMDN Kulasekara,1,0,Victoria,"Simonds Stadium, South Geelong"
7,2,"[Australia, Sri Lanka]",Australia,1.2,M Klinger,KMDN Kulasekara,1,0,Victoria,"Simonds Stadium, South Geelong"
8,2,"[Australia, Sri Lanka]",Australia,1.3,AJ Finch,KMDN Kulasekara,2,0,Victoria,"Simonds Stadium, South Geelong"
9,2,"[Australia, Sri Lanka]",Australia,1.4,AJ Finch,KMDN Kulasekara,2,0,Victoria,"Simonds Stadium, South Geelong"

In [29]:
delivery_df['bowling_team'] = delivery_df.apply(
    lambda row: [team for team in row['teams'] if team != row['batting_team']][0], 
    axis=1
)

In [30]:
delivery_df

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,"[Australia, Sri Lanka]",Australia,0.1,M Klinger,SL Malinga,0,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
1,2,"[Australia, Sri Lanka]",Australia,0.2,M Klinger,SL Malinga,1,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
2,2,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,0,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
3,2,"[Australia, Sri Lanka]",Australia,0.4,AJ Finch,SL Malinga,4,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
4,2,"[Australia, Sri Lanka]",Australia,0.5,AJ Finch,SL Malinga,1,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
...,...,...,...,...,...,...,...,...,...,...,...
553781,5055,"[Sri Lanka, Australia]",Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia
553782,5055,"[Sri Lanka, Australia]",Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,Australia
553783,5055,"[Sri Lanka, Australia]",Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,Australia
553784,5055,"[Sri Lanka, Australia]",Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,Australia
553785,5055,"[Sri Lanka, Australia]",Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia

In [31]:
delivery_df.drop(columns=['teams'],inplace=True)

In [32]:
delivery_df

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,Australia,0.1,M Klinger,SL Malinga,0,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
1,2,Australia,0.2,M Klinger,SL Malinga,1,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
2,2,Australia,0.3,AJ Finch,SL Malinga,0,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
3,2,Australia,0.4,AJ Finch,SL Malinga,4,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
4,2,Australia,0.5,AJ Finch,SL Malinga,1,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
...,...,...,...,...,...,...,...,...,...,...
553781,5055,Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia
553782,5055,Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,Australia
553783,5055,Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,Australia
553784,5055,Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,Australia
553785,5055,Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia

In [33]:
delivery_df['batting_team'].unique()

array(['Australia', 'Hong Kong', 'Bangladesh', 'New Zealand',
       'South Africa', 'England', 'West Indies', 'India', 'Sri Lanka',
       'Scotland', 'Oman', 'Pakistan', 'Papua New Guinea',
       'United Arab Emirates', 'Netherlands', 'Ireland', 'Zimbabwe',
       'Thailand', 'Uganda', 'Malaysia', 'Nepal', 'China', 'Kuwait',
       'Vanuatu', 'Philippines', 'United States of America', 'Germany',
       'Botswana', 'Namibia', 'Mozambique', 'Sierra Leone', 'Nigeria',
       'Tanzania', 'Japan', 'Indonesia', 'Fiji', 'Samoa', 'Ghana',
       'Kenya', 'Guernsey', 'Denmark', 'Jersey', 'Italy', 'Norway',
       'Maldives', 'Mali', 'Singapore', 'Bermuda', 'Canada',
       'Cayman Islands', 'Bhutan', 'Qatar', 'Iran', 'Austria',
       'Isle of Man', 'Luxembourg', 'Czech Republic', 'Rwanda', 'Serbia',
       'Belgium', 'France', 'Eswatini', 'Cameroon', 'Hungary', 'Estonia',
       'Cyprus', 'Malta', 'Argentina', 'Seychelles', 'Malawi', 'Lesotho',
       'Swaziland', 'Bahrain', 'Belize', 'Bahamas', 'Panama', 'Barbados',
       'Saudi Arabia', 'Spain', 'Gibraltar', 'Romania', 'Bulgaria',
       'Sweden', 'Brazil', 'Portugal', 'Israel', 'Finland', 'Croatia',
       'Turkey', 'Switzerland', 'Slovenia', 'Cook Islands', 'South Korea',
       'St Helena', 'Gambia', 'Cambodia', 'Myanmar', 'Mexico',
       'Costa Rica', 'Mongolia', 'Greece', 'Ivory Coast', 'Suriname',
       'Turks and Caicos Island', 'Timor-Leste', 'Zambia'], dtype=object)

In [34]:
teams = [
    'Australia',
    'India',
    'Zimbabwe',
    'Bangladesh',
    'New Zealand',
    'South Africa',
    'England',
    'West Indies',
    'Afghanistan',
    'Pakistan',
    'Sri Lanka'    
]

In [35]:
delivery_df = delivery_df[delivery_df['batting_team'].isin(teams)]
delivery_df = delivery_df[delivery_df['bowling_team'].isin(teams)]

In [36]:
delivery_df

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,Australia,0.1,M Klinger,SL Malinga,0,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
1,2,Australia,0.2,M Klinger,SL Malinga,1,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
2,2,Australia,0.3,AJ Finch,SL Malinga,0,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
3,2,Australia,0.4,AJ Finch,SL Malinga,4,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
4,2,Australia,0.5,AJ Finch,SL Malinga,1,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
...,...,...,...,...,...,...,...,...,...,...
553781,5055,Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia
553782,5055,Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,Australia
553783,5055,Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,Australia
553784,5055,Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,Australia
553785,5055,Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia

In [37]:
delivery_df.drop(columns=['batsman'],inplace=True)
delivery_df.drop(columns=['bowler'],inplace=True)

delivery_df

,match_id,batting_team,ball,runs,player_dismissed,city,venue,bowling_team
0,2,Australia,0.1,0,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
1,2,Australia,0.2,1,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
2,2,Australia,0.3,0,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
3,2,Australia,0.4,4,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
4,2,Australia,0.5,1,0,Victoria,"Simonds Stadium, South Geelong",Sri Lanka
...,...,...,...,...,...,...,...,...
553781,5055,Sri Lanka,19.3,1,0,Colombo,R Premadasa Stadium,Australia
553782,5055,Sri Lanka,19.4,0,0,Colombo,R Premadasa Stadium,Australia
553783,5055,Sri Lanka,19.5,0,DM de Silva,Colombo,R Premadasa Stadium,Australia
553784,5055,Sri Lanka,19.6,2,0,Colombo,R Premadasa Stadium,Australia
553785,5055,Sri Lanka,19.7,1,0,Colombo,R Premadasa Stadium,Australia

In [38]:
pickle.dump(delivery_df, open('dataset_level2.pkl', 'wb'))

In [4]:
import pickle
matches = pickle.load(open('dataset_level2.pkl', 'rb'))
matches.tail(10)

,match_id,batting_team,ball,runs,player_dismissed,city,venue,bowling_team
553776,5055,Sri Lanka,18.6,1,0,Colombo,R Premadasa Stadium,Australia
553777,5055,Sri Lanka,18.7,1,0,Colombo,R Premadasa Stadium,Australia
553778,5055,Sri Lanka,18.8,1,0,Colombo,R Premadasa Stadium,Australia
553779,5055,Sri Lanka,19.1,1,0,Colombo,R Premadasa Stadium,Australia
553780,5055,Sri Lanka,19.2,0,0,Colombo,R Premadasa Stadium,Australia
553781,5055,Sri Lanka,19.3,1,0,Colombo,R Premadasa Stadium,Australia
553782,5055,Sri Lanka,19.4,0,0,Colombo,R Premadasa Stadium,Australia
553783,5055,Sri Lanka,19.5,0,DM de Silva,Colombo,R Premadasa Stadium,Australia
553784,5055,Sri Lanka,19.6,2,0,Colombo,R Premadasa Stadium,Australia
553785,5055,Sri Lanka,19.7,1,0,Colombo,R Premadasa Stadium,Australia

In [3]:
matches.isnull().sum()

match_id            0
batting_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
bowling_team        0
dtype: int64

In [8]:
final_cities = matches['city'].value_counts() [matches['city'].value_counts()>600].index.tolist()

In [9]:
matches = matches[matches['city'].isin(final_cities)]

In [10]:
matches

,match_id,batting_team,ball,runs,player_dismissed,city,venue,bowling_team
251,8,Bangladesh,0.1,0,0,Napier,McLean Park,New Zealand
252,8,Bangladesh,0.2,0,0,Napier,McLean Park,New Zealand
253,8,Bangladesh,0.3,0,0,Napier,McLean Park,New Zealand
254,8,Bangladesh,0.4,0,0,Napier,McLean Park,New Zealand
255,8,Bangladesh,0.5,1,0,Napier,McLean Park,New Zealand
...,...,...,...,...,...,...,...,...
553781,5055,Sri Lanka,19.3,1,0,Colombo,R Premadasa Stadium,Australia
553782,5055,Sri Lanka,19.4,0,0,Colombo,R Premadasa Stadium,Australia
553783,5055,Sri Lanka,19.5,0,DM de Silva,Colombo,R Premadasa Stadium,Australia
553784,5055,Sri Lanka,19.6,2,0,Colombo,R Premadasa Stadium,Australia
553785,5055,Sri Lanka,19.7,1,0,Colombo,R Premadasa Stadium,Australia

In [ ]:
# current score
matches['current_score'] = matches.groupby('match_id')['runs'].cumsum()

In [14]:
matches

,match_id,batting_team,ball,runs,player_dismissed,city,venue,bowling_team,current_score
251,8,Bangladesh,0.1,0,0,Napier,McLean Park,New Zealand,0
252,8,Bangladesh,0.2,0,0,Napier,McLean Park,New Zealand,0
253,8,Bangladesh,0.3,0,0,Napier,McLean Park,New Zealand,0
254,8,Bangladesh,0.4,0,0,Napier,McLean Park,New Zealand,0
255,8,Bangladesh,0.5,1,0,Napier,McLean Park,New Zealand,1
...,...,...,...,...,...,...,...,...,...
553781,5055,Sri Lanka,19.3,1,0,Colombo,R Premadasa Stadium,Australia,125
553782,5055,Sri Lanka,19.4,0,0,Colombo,R Premadasa Stadium,Australia,125
553783,5055,Sri Lanka,19.5,0,DM de Silva,Colombo,R Premadasa Stadium,Australia,125
553784,5055,Sri Lanka,19.6,2,0,Colombo,R Premadasa Stadium,Australia,127
553785,5055,Sri Lanka,19.7,1,0,Colombo,R Premadasa Stadium,Australia,128

In [16]:
# Left balls
# spliting balls ( 1.1 -> 1 over 1 ball)
matches['over'] = matches['ball'].apply(lambda x: int(str(x).split('.')[0]))
matches['ball_in_over'] = matches['ball'].apply(lambda x: int(str(x).split('.')[1]))

# total balls bowled so far
matches['balls_bowled'] = matches['over'] * 6 + matches['ball_in_over'].apply(lambda x : min(x,6))

# Balls left = 120 - balls bowled
matches['balls_left'] = 120 - matches['balls_bowled'].clip(0, 120)

matches

,match_id,batting_team,ball,runs,player_dismissed,city,venue,bowling_team,current_score,over,ball_in_over,balls_bowled,balls_left
251,8,Bangladesh,0.1,0,0,Napier,McLean Park,New Zealand,0,0,1,1,119
252,8,Bangladesh,0.2,0,0,Napier,McLean Park,New Zealand,0,0,2,2,118
253,8,Bangladesh,0.3,0,0,Napier,McLean Park,New Zealand,0,0,3,3,117
254,8,Bangladesh,0.4,0,0,Napier,McLean Park,New Zealand,0,0,4,4,116
255,8,Bangladesh,0.5,1,0,Napier,McLean Park,New Zealand,1,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...,...
553781,5055,Sri Lanka,19.3,1,0,Colombo,R Premadasa Stadium,Australia,125,19,3,117,3
553782,5055,Sri Lanka,19.4,0,0,Colombo,R Premadasa Stadium,Australia,125,19,4,118,2
553783,5055,Sri Lanka,19.5,0,DM de Silva,Colombo,R Premadasa Stadium,Australia,125,19,5,119,1
553784,5055,Sri Lanka,19.6,2,0,Colombo,R Premadasa Stadium,Australia,127,19,6,120,0
553785,5055,Sri Lanka,19.7,1,0,Colombo,R Premadasa Stadium,Australia,128,19,7,120,0

In [17]:
# wickets left
matches['player_dismissed'] = matches['player_dismissed'].apply(lambda x:0 if x=='0' else 1)
matches['player_dismissed'] = matches['player_dismissed'].astype('int')
matches['player_dismissed'] = matches.groupby('match_id')['player_dismissed'].cumsum()
matches['wickets_left'] = 10 - matches['player_dismissed']

In [18]:
matches

,match_id,batting_team,ball,runs,player_dismissed,city,venue,bowling_team,current_score,over,ball_in_over,balls_bowled,balls_left,wickets_left
251,8,Bangladesh,0.1,0,0,Napier,McLean Park,New Zealand,0,0,1,1,119,10
252,8,Bangladesh,0.2,0,0,Napier,McLean Park,New Zealand,0,0,2,2,118,10
253,8,Bangladesh,0.3,0,0,Napier,McLean Park,New Zealand,0,0,3,3,117,10
254,8,Bangladesh,0.4,0,0,Napier,McLean Park,New Zealand,0,0,4,4,116,10
255,8,Bangladesh,0.5,1,0,Napier,McLean Park,New Zealand,1,0,5,5,115,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553781,5055,Sri Lanka,19.3,1,8,Colombo,R Premadasa Stadium,Australia,125,19,3,117,3,2
553782,5055,Sri Lanka,19.4,0,8,Colombo,R Premadasa Stadium,Australia,125,19,4,118,2,2
553783,5055,Sri Lanka,19.5,0,9,Colombo,R Premadasa Stadium,Australia,125,19,5,119,1,1
553784,5055,Sri Lanka,19.6,2,9,Colombo,R Premadasa Stadium,Australia,127,19,6,120,0,1
553785,5055,Sri Lanka,19.7,1,9,Colombo,R Premadasa Stadium,Australia,128,19,7,120,0,1

In [19]:
matches['current_run_rate'] = (
    matches['current_score'] / (matches['balls_bowled'] / 6)
).replace([float('inf'), float('nan')], 0).round(2)

matches

,match_id,batting_team,ball,runs,player_dismissed,city,venue,bowling_team,current_score,over,ball_in_over,balls_bowled,balls_left,wickets_left,current_run_rate
251,8,Bangladesh,0.1,0,0,Napier,McLean Park,New Zealand,0,0,1,1,119,10,0.00
252,8,Bangladesh,0.2,0,0,Napier,McLean Park,New Zealand,0,0,2,2,118,10,0.00
253,8,Bangladesh,0.3,0,0,Napier,McLean Park,New Zealand,0,0,3,3,117,10,0.00
254,8,Bangladesh,0.4,0,0,Napier,McLean Park,New Zealand,0,0,4,4,116,10,0.00
255,8,Bangladesh,0.5,1,0,Napier,McLean Park,New Zealand,1,0,5,5,115,10,1.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553781,5055,Sri Lanka,19.3,1,8,Colombo,R Premadasa Stadium,Australia,125,19,3,117,3,2,6.41
553782,5055,Sri Lanka,19.4,0,8,Colombo,R Premadasa Stadium,Australia,125,19,4,118,2,2,6.36
553783,5055,Sri Lanka,19.5,0,9,Colombo,R Premadasa Stadium,Australia,125,19,5,119,1,1,6.30
553784,5055,Sri Lanka,19.6,2,9,Colombo,R Premadasa Stadium,Australia,127,19,6,120,0,1,6.35
553785,5055,Sri Lanka,19.7,1,9,Colombo,R Premadasa Stadium,Australia,128,19,7,120,0,1,6.40