In [1]:
import os
import yaml
import pandas as pd
from pandas import json_normalize
from yaml import safe_load
from tqdm import tqdm

In [28]:
# Extract File Names
folder_path = 'data'

file_names = [f for f in os.listdir(folder_path) if f.endswith('.yaml')]

print(f"Total files found: {len(file_names)}")
print("First 5 files:", file_names[:5])

Total files found: 5055
First 5 files: ['1001349.yaml', '1001351.yaml', '1001353.yaml', '1004729.yaml', '1007655.yaml']

In [29]:
# to extract yaml files 
final_df = pd.DataFrame()
counter = 1

for file_name in tqdm(file_names, desc="Loading match files"):
    full_path = os.path.join(folder_path, file_name)
    
    with open(full_path, 'r') as f:
        df = pd.json_normalize(safe_load(f), max_level=1)
        df['match_id'] = counter
        final_df = pd.concat([final_df, df], ignore_index=True)
        counter += 1

final_df

Loading match files: 100%|██████████| 5055/5055 [14:04<00:00,  5.99it/s]

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.dates,info.gender,info.match_type,info.outcome,info.overs,...,info.teams,info.toss,info.umpires,info.venue,match_id,info.city,info.match_type_number,info.neutral_venue,info.supersubs,info.bowl_out
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-18,2,6,[2017-02-17],male,T20,"{'by': {'wickets': 5}, 'winner': 'Sri Lanka'}",20,...,"[Australia, Sri Lanka]","{'decision': 'field', 'winner': 'Sri Lanka'}","[MD Martell, P Wilson]",Melbourne Cricket Ground,1,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-19,2,6,[2017-02-19],male,T20,"{'by': {'wickets': 2}, 'winner': 'Sri Lanka'}",20,...,"[Australia, Sri Lanka]","{'decision': 'field', 'winner': 'Sri Lanka'}","[SD Fry, SJ Nogajski]","Simonds Stadium, South Geelong",2,Victoria,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-23,1,6,[2017-02-22],male,T20,"{'by': {'runs': 41}, 'winner': 'Australia'}",20,...,"[Australia, Sri Lanka]","{'decision': 'field', 'winner': 'Sri Lanka'}","[MD Martell, P Wilson]",Adelaide Oval,3,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",0.91,2016-09-12,1,6,[2016-09-05],male,T20,"{'by': {'runs': 40}, 'winner': 'Hong Kong'}",20,...,"[Ireland, Hong Kong]","{'decision': 'bat', 'winner': 'Hong Kong'}","[R Black, AJ Neill]","Bready Cricket Club, Magheramason",4,Londonderry,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.91,2016-06-19,1,6,[2016-06-18],male,T20,"{'by': {'runs': 2}, 'winner': 'Zimbabwe'}",20,...,"[Zimbabwe, India]","{'decision': 'field', 'winner': 'India'}","[TJ Matibiri, RB Tiffin]",Harare Sports Club,5,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5050,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.91,2016-03-05,2,6,[2016-03-04],male,T20,"{'by': {'wickets': 6}, 'winner': 'Pakistan'}",20,...,"[Pakistan, Sri Lanka]","{'decision': 'field', 'winner': 'Pakistan'}","[AK Chaudhary, Enamul Haque]",Shere Bangla National Stadium,5051,Mirpur,NaN,1.0,NaN,NaN
5051,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",0.91,2016-03-08,1,6,[2016-03-06],male,T20,"{'by': {'wickets': 8}, 'winner': 'India'}",20,...,"[Bangladesh, India]","{'decision': 'field', 'winner': 'India'}","[RSA Palliyaguruge, Shozab Raza]",Shere Bangla National Stadium,5052,Mirpur,NaN,NaN,NaN,NaN
5052,"[{'1st innings': {'team': 'Netherlands', 'deli...",0.91,2016-02-03,1,6,[2016-02-03],male,T20,"{'by': {'runs': 84}, 'winner': 'Netherlands'}",20,...,"[United Arab Emirates, Netherlands]","{'decision': 'field', 'winner': 'United Arab E...","[CK Nandan, Sarika Prasad]",ICC Academy,5053,Dubai,NaN,NaN,NaN,NaN
5053,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2016-09-12,1,6,[2016-09-06],male,T20,"{'by': {'runs': 85}, 'winner': 'Australia'}",20,...,"[Sri Lanka, Australia]","{'decision': 'field', 'winner': 'Sri Lanka'}","[REJ Martinesz, RR Wimalasiri]",Pallekele International Cricket Stadium,5054,NaN,NaN,NaN,NaN,NaN
5054,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",0.91,2016-09-12,1,6,[2016-09-09],male,T20,"{'by': {'wickets': 4}, 'winner': 'Australia'}",20,...,"[Sri Lanka, Australia]","{'decision': 'bat', 'winner': 'Sri Lanka'}","[REJ Martinesz, RSA Palliyaguruge]",R Premadasa Stadium,5055,Colombo,NaN,NaN,NaN,NaN

In [33]:
final_df.info(22)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5055 entries, 0 to 5054
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   innings                 5055 non-null   object
 1   meta.data_version       5055 non-null   float64
 2   meta.created            5055 non-null   object
 3   meta.revision           5055 non-null   int64
 4   info.balls_per_over     5055 non-null   int64
 5   info.dates              5055 non-null   object
 6   info.gender             5055 non-null   object
 7   info.match_type         5055 non-null   object
 8   info.outcome            5055 non-null   object
 9   info.overs              5055 non-null   int64
 10  info.player_of_match    4572 non-null   object
 11  info.players            5055 non-null   object
 12  info.registry           5055 non-null   object
 13  info.teams              5055 non-null   object
 14  info.toss               5055 non-null   object
 15  info.umpires            4750 non-null   object
 16  info.venue              5055 non-null   object
 17  match_id                5055 non-null   int64
 18  info.city               4876 non-null   object
 19  info.match_type_number  4380 non-null   float64
 20  info.neutral_venue      283 non-null    float64
 21  info.supersubs          1 non-null      object
 22  info.bowl_out           2 non-null      object
dtypes: float64(3), int64(4), object(16)
memory usage: 908.4+ KB

In [35]:
# relevant columns
final_df = final_df[[
    'match_id',
    'info.dates',
    'info.venue',
    'info.city',
    'info.gender',
    'info.match_type',
    'info.overs',
    'info.teams',
    'info.umpires',
    'info.toss',
    'info.outcome',
    'innings',
]].rename(columns={
    'info.dates'      : 'date',
    'info.venue'      : 'venue',
    'info.city'       : 'city',
    'info.gender'     : 'gender',
    'info.match_type' : 'match_type',
    'info.overs'      : 'overs',
    'info.teams'      : 'teams',
    'info.umpires'    : 'umpires',
    'info.toss'       : 'toss',
    'info.outcome'    : 'outcome',
})

In [36]:
final_df.head()

,match_id,date,venue,city,gender,match_type,overs,teams,umpires,toss,outcome,innings
0,1,[2017-02-17],Melbourne Cricket Ground,NaN,male,T20,20,"[Australia, Sri Lanka]","[MD Martell, P Wilson]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'wickets': 5}, 'winner': 'Sri Lanka'}","[{'1st innings': {'team': 'Australia', 'delive..."
1,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,T20,20,"[Australia, Sri Lanka]","[SD Fry, SJ Nogajski]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'wickets': 2}, 'winner': 'Sri Lanka'}","[{'1st innings': {'team': 'Australia', 'delive..."
2,3,[2017-02-22],Adelaide Oval,NaN,male,T20,20,"[Australia, Sri Lanka]","[MD Martell, P Wilson]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'runs': 41}, 'winner': 'Australia'}","[{'1st innings': {'team': 'Australia', 'delive..."
3,4,[2016-09-05],"Bready Cricket Club, Magheramason",Londonderry,male,T20,20,"[Ireland, Hong Kong]","[R Black, AJ Neill]","{'decision': 'bat', 'winner': 'Hong Kong'}","{'by': {'runs': 40}, 'winner': 'Hong Kong'}","[{'1st innings': {'team': 'Hong Kong', 'delive..."
4,5,[2016-06-18],Harare Sports Club,NaN,male,T20,20,"[Zimbabwe, India]","[TJ Matibiri, RB Tiffin]","{'decision': 'field', 'winner': 'India'}","{'by': {'runs': 2}, 'winner': 'Zimbabwe'}","[{'1st innings': {'team': 'Zimbabwe', 'deliver..."

In [37]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5055 entries, 0 to 5054
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   match_id    5055 non-null   int64
 1   date        5055 non-null   object
 2   venue       5055 non-null   object
 3   city        4876 non-null   object
 4   gender      5055 non-null   object
 5   match_type  5055 non-null   object
 6   overs       5055 non-null   int64
 7   teams       5055 non-null   object
 8   umpires     4750 non-null   object
 9   toss        5055 non-null   object
 10  outcome     5055 non-null   object
 11  innings     5055 non-null   object
dtypes: int64(2), object(10)
memory usage: 474.0+ KB

In [38]:
final_df = final_df[(final_df['overs'] == 20) & (final_df['match_type'] == 'T20')]

print(f"Shape after filtering: {final_df.shape}")
final_df.head()

Shape after filtering: (5040, 12)

,match_id,date,venue,city,gender,match_type,overs,teams,umpires,toss,outcome,innings
0,1,[2017-02-17],Melbourne Cricket Ground,NaN,male,T20,20,"[Australia, Sri Lanka]","[MD Martell, P Wilson]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'wickets': 5}, 'winner': 'Sri Lanka'}","[{'1st innings': {'team': 'Australia', 'delive..."
1,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,T20,20,"[Australia, Sri Lanka]","[SD Fry, SJ Nogajski]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'wickets': 2}, 'winner': 'Sri Lanka'}","[{'1st innings': {'team': 'Australia', 'delive..."
2,3,[2017-02-22],Adelaide Oval,NaN,male,T20,20,"[Australia, Sri Lanka]","[MD Martell, P Wilson]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'runs': 41}, 'winner': 'Australia'}","[{'1st innings': {'team': 'Australia', 'delive..."
3,4,[2016-09-05],"Bready Cricket Club, Magheramason",Londonderry,male,T20,20,"[Ireland, Hong Kong]","[R Black, AJ Neill]","{'decision': 'bat', 'winner': 'Hong Kong'}","{'by': {'runs': 40}, 'winner': 'Hong Kong'}","[{'1st innings': {'team': 'Hong Kong', 'delive..."
4,5,[2016-06-18],Harare Sports Club,NaN,male,T20,20,"[Zimbabwe, India]","[TJ Matibiri, RB Tiffin]","{'decision': 'field', 'winner': 'India'}","{'by': {'runs': 2}, 'winner': 'Zimbabwe'}","[{'1st innings': {'team': 'Zimbabwe', 'deliver..."

In [39]:
final_df = final_df.dropna()

print(f"Shape after dropping nulls: {final_df.shape}")
final_df.head()

Shape after dropping nulls: (4557, 12)

,match_id,date,venue,city,gender,match_type,overs,teams,umpires,toss,outcome,innings
1,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,T20,20,"[Australia, Sri Lanka]","[SD Fry, SJ Nogajski]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'wickets': 2}, 'winner': 'Sri Lanka'}","[{'1st innings': {'team': 'Australia', 'delive..."
3,4,[2016-09-05],"Bready Cricket Club, Magheramason",Londonderry,male,T20,20,"[Ireland, Hong Kong]","[R Black, AJ Neill]","{'decision': 'bat', 'winner': 'Hong Kong'}","{'by': {'runs': 40}, 'winner': 'Hong Kong'}","[{'1st innings': {'team': 'Hong Kong', 'delive..."
7,8,[2017-01-03],McLean Park,Napier,male,T20,20,"[New Zealand, Bangladesh]","[SB Haig, WR Knights]","{'decision': 'bat', 'winner': 'Bangladesh'}","{'by': {'wickets': 6}, 'winner': 'New Zealand'}","[{'1st innings': {'team': 'Bangladesh', 'deliv..."
8,9,[2017-01-06],Bay Oval,Mount Maunganui,male,T20,20,"[New Zealand, Bangladesh]","[CM Brown, SB Haig]","{'decision': 'field', 'winner': 'Bangladesh'}","{'by': {'runs': 47}, 'winner': 'New Zealand'}","[{'1st innings': {'team': 'New Zealand', 'deli..."
9,10,[2017-01-08],Bay Oval,Mount Maunganui,male,T20,20,"[New Zealand, Bangladesh]","[CM Brown, WR Knights]","{'decision': 'field', 'winner': 'Bangladesh'}","{'by': {'runs': 27}, 'winner': 'New Zealand'}","[{'1st innings': {'team': 'New Zealand', 'deli..."

In [40]:
final_df['gender'].value_counts()

gender
male      2878
female    1679
Name: count, dtype: int64

In [45]:
import pickle

pickle.dump(final_df, open('dataset_level1.pkl', 'wb'))

In [2]:
import pickle
df = pickle.load(open('dataset_level1.pkl', 'rb'))
df.head()

,match_id,date,venue,city,gender,match_type,overs,teams,umpires,toss,outcome,innings
1,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,T20,20,"[Australia, Sri Lanka]","[SD Fry, SJ Nogajski]","{'decision': 'field', 'winner': 'Sri Lanka'}","{'by': {'wickets': 2}, 'winner': 'Sri Lanka'}","[{'1st innings': {'team': 'Australia', 'delive..."
3,4,[2016-09-05],"Bready Cricket Club, Magheramason",Londonderry,male,T20,20,"[Ireland, Hong Kong]","[R Black, AJ Neill]","{'decision': 'bat', 'winner': 'Hong Kong'}","{'by': {'runs': 40}, 'winner': 'Hong Kong'}","[{'1st innings': {'team': 'Hong Kong', 'delive..."
7,8,[2017-01-03],McLean Park,Napier,male,T20,20,"[New Zealand, Bangladesh]","[SB Haig, WR Knights]","{'decision': 'bat', 'winner': 'Bangladesh'}","{'by': {'wickets': 6}, 'winner': 'New Zealand'}","[{'1st innings': {'team': 'Bangladesh', 'deliv..."
8,9,[2017-01-06],Bay Oval,Mount Maunganui,male,T20,20,"[New Zealand, Bangladesh]","[CM Brown, SB Haig]","{'decision': 'field', 'winner': 'Bangladesh'}","{'by': {'runs': 47}, 'winner': 'New Zealand'}","[{'1st innings': {'team': 'New Zealand', 'deli..."
9,10,[2017-01-08],Bay Oval,Mount Maunganui,male,T20,20,"[New Zealand, Bangladesh]","[CM Brown, WR Knights]","{'decision': 'field', 'winner': 'Bangladesh'}","{'by': {'runs': 27}, 'winner': 'New Zealand'}","[{'1st innings': {'team': 'New Zealand', 'deli..."

In [7]:
all_rows = []

for _, row in tqdm(df.iterrows(), desc="Extracting ball by ball", total=len(df)):

    innings = row['innings']

    # We only want the 1st innings
    if not innings or len(innings) == 0:
        continue

    first_innings = innings[0]  # 0 = 1st innings, 1 = 2nd innings

    for inning_name, inning_content in first_innings.items():

        batting_team = inning_content.get('team', None)
        deliveries   = inning_content.get('deliveries', [])

        # Figure out bowling team
        teams        = row['teams']
        bowling_team = [t for t in teams if t != batting_team][0] if teams else None

        cumulative_runs    = 0
        cumulative_wickets = 0

        for delivery in deliveries:
            for ball, ball_data in delivery.items():

                runs_total          = ball_data.get('runs', {}).get('total', 0)
                cumulative_runs    += runs_total
                cumulative_wickets += 1 if ball_data.get('wicket') else 0

                all_rows.append({
                    'match_id'           : row['match_id'],
                    'date'               : row['date'],
                    'venue'              : row['venue'],
                    'city'               : row['city'],
                    'gender'             : row['gender'],
                    'toss_winner'        : row['toss'].get('winner', None),
                    'toss_decision'      : row['toss'].get('decision', None),
                    'winner'             : row['outcome'].get('winner', None),
                    'batting_team'       : batting_team,
                    'bowling_team'       : bowling_team,
                    'ball'               : ball,
                    'runs_batsman'       : ball_data.get('runs', {}).get('batsman', 0),
                    'runs_extras'        : ball_data.get('runs', {}).get('extras', 0),
                    'runs_total'         : runs_total,
                    'wicket'             : 1 if ball_data.get('wicket') else 0,
                    'cumulative_runs'    : cumulative_runs,
                    'cumulative_wickets' : cumulative_wickets,
                })

# Convert to DataFrame
ball_by_ball_df = pd.DataFrame(all_rows)

print(f"Shape: {ball_by_ball_df.shape}")
ball_by_ball_df.head(10)

Extracting ball by ball: 100%|██████████| 4557/4557 [00:19<00:00, 239.05it/s]

Shape: (553786, 17)

,match_id,date,venue,city,gender,toss_winner,toss_decision,winner,batting_team,bowling_team,ball,runs_batsman,runs_extras,runs_total,wicket,cumulative_runs,cumulative_wickets
0,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,Sri Lanka,field,Sri Lanka,Australia,Sri Lanka,0.1,0,0,0,0,0,0
1,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,Sri Lanka,field,Sri Lanka,Australia,Sri Lanka,0.2,1,0,1,0,1,0
2,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,Sri Lanka,field,Sri Lanka,Australia,Sri Lanka,0.3,0,0,0,0,1,0
3,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,Sri Lanka,field,Sri Lanka,Australia,Sri Lanka,0.4,4,0,4,0,5,0
4,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,Sri Lanka,field,Sri Lanka,Australia,Sri Lanka,0.5,0,1,1,0,6,0
5,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,Sri Lanka,field,Sri Lanka,Australia,Sri Lanka,0.6,1,0,1,0,7,0
6,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,Sri Lanka,field,Sri Lanka,Australia,Sri Lanka,1.1,0,1,1,0,8,0
7,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,Sri Lanka,field,Sri Lanka,Australia,Sri Lanka,1.2,1,0,1,0,9,0
8,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,Sri Lanka,field,Sri Lanka,Australia,Sri Lanka,1.3,2,0,2,0,11,0
9,2,[2017-02-19],"Simonds Stadium, South Geelong",Victoria,male,Sri Lanka,field,Sri Lanka,Australia,Sri Lanka,1.4,2,0,2,0,13,0